### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by anqi-lu** [anqi-lu/TMDB-keywords#1]
Use python to process data for use of visualization
- [ ] aggregate keywords (example: "friends" and "friendship" will be merged together)
- [x] Count keywords by year
- [x] Count keywords by genre

**Comment by emilyw15** [comment]
The professor suggested I aggregate using a Node.js script using Datalib. See https://github.com/vega/datalib/wiki/Group-By. Maybe you could use this for some aggregation and counting.

**Comment by anqi-lu** [comment]
That's awesome - I'll look into it! Thank you so much! @emilyw15
